spring:
  application.name: todo-sample

management:
  port: 9001
  address: 127.0.0.1

endpoints:
  shutdown

server:
  port: 8080

spring:
  thymeleaf:
    cache: false

#  datasource:
#    url: jdbc:h2:mem:todo;
#    username: sa
#    password:
#    driverClassName: org.h2.Driver
#
#  jpa:
#    database: H2
#    show-sql: true
#    hibernate:
#      ddl-auto: create-drop
#      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
